version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend-gptclone
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

volumes:
  node_modules: